### ISSUE TITLE
Recognition of xOsmunasium nothgen. nov. [PASSED]

### ISSUE THREAD

**Issue by choess** [pteridogroup/ppg#10]
### Name of taxon

xOsmunasium

### Rank of taxon

Nothogenus

### Approximate number of species affected

1

### Description of change

This proposal recognizes the nothogenus x _Osmunasium_ for hybrids between the genera _Osmunda_ and _Plenasium_ (Osmundaceae). It contains one species: x _Osmunasium_ x _mildei_, a hybrid between _Osmunda japonica_ and _Plenasium vachellii_.

### Reason for change

Nothotaxa are planned to be recognized in PPG II. If _Claytosmunda_ and _Plenasium_ are separated from _Osmunda_ s.s. as genera, as in PPG I, this species becomes an intergeneric hybrid.

Spore viability of the hybrid is low, and it is of very uncommon occurrence in Asia. (Tsutsumi et al. 2012)

The first valid name for this nothogenus is x _Osmunasium_ Hong M.Liu, Schuettp. & H.Schneid. (Liu et al. 2020)

Alternatively, PPG II could revert to recognizing a broadly circumscribed but monophyletic _Osmunda_ which would render this nothogenus superfluous. However, _Claytosmunda_ and _Plenasium_ are believed to have diverged from _Osmunda_ s.s. in the Jurassic and Cretaceous, respectively, and they can be identified and distinguished in the fossil record. (Bomfleur et al. 2017).

Bomfleur B, Grimm GW, McLoughlin S. 2017. The fossil Osmundales (royal ferns)—a phylogenetic network analyses, revised taxonomy, and evolutionary classification of anatomically preserved trunks and rhizomes. PeerJ 5: 3433. [https://doi.org/10.7717/peerj.3433](https://doi.org/10.7717/peerj.3433)

Hong-Mei Liu, Eric Schuettpelz, Harald Schneider. 2020. Evaluating the status of fern and lycophyte nothotaxa in the context of the Pteridophyte Phylogeny Group classification (PPG I). Journal of Systematics and Evolution 58(6): 988-1002. [https://doi.org/10.1111/jse.12641](https://doi.org/10.1111/jse.12641)

C. Tsutsumi, Y. Hirayama, M. Kato, Y. Yatabe-Kakugawa, S-Z. Zhang. 2012.
Molecular Evidence on the Origin of Osmunda ×mildei (Osmundaceae). American Fern Journal 102(1):55-68.[https://doi.org/10.1640/0002-8444-102.1.55](https://doi.org/10.1640/0002-8444-102.1.55)

### Reference(s) for publication of the name

Hong-Mei Liu, Eric Schuettpelz, Harald Schneider. 2020. Evaluating the status of fern and lycophyte nothotaxa in the context of the Pteridophyte Phylogeny Group classification (PPG I). Journal of Systematics and Evolution 58(6): 988-1002. [https://doi.org/10.1111/jse.12641](https://doi.org/10.1111/jse.12641)

### List the numbers of any related issues

#9

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by schwartsburd** [comment]
Looks convincing to me. Although I personally think sometimes there is an over-exageration on the number of recognized genera, in this specific case the genera represent old lineages that diverged apart hundreds of millions of years ago. I am in favor of this proposal.

**Comment by joelnitta** [comment]
FYI, please see the related discussion about circumscription of _Osmunda_: https://github.com/pteridogroup/ppg/discussions/24

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 1 (voting period July 2023). A total of 46 votes were cast. There were 42 'Yes' votes (91.3%) and 4 'No' votes (8.7%). The proposal passes.

**Comment by joelnitta** [comment]
Already implemented in data, closing.
