### ISSUE TITLE
Rescue of Spicantopsis (Blechnaceae, Polypodiopsida) [PASSED]

### ISSUE THREAD

**Issue by Sonimomi** [pteridogroup/ppg#12]
### Name of taxon

Spicantopsis Nakai

### Rank of taxon

Genus

### Approximate number of species affected

3

### Description of change

The genus _Spicantopsis_ has been resurrected to accommodate three species previously in the genus _Struthiopteris_, which formed a non-monophyletic group.
This change is presented by the Blechnaceae working group (S. Molino, A. Gasper, V.A.O. Dittrich, R. Vázquez, G. Santos, R. Medina).

### Reason for change

After a morphoanatomical and phylogenetic study of all the species that made up the genus _Struthiopteris_ according to Gasper et al. (2016, 2017) and PPG I (2016), it was resolved that this genus did not form a monophyletic group, and that it was more convenient to resurrect the genus _Spicantopsis_ for three of the species (Nakai, 1933, Molino, 2019). Nakai (1933) argued for the existence of this genus on the fact that the pattern of development and distribution of stomata was distinctive; however, there were authors who considered that the existence of that single character was not sufficient to maintain a distinct genus (e.g., Tagawa, 1952). However, in Molino et al. (2019, 2020) more characters such as petiole color, pinna anatomical profile, spores, sporangia, sorus morphology and molecular phylogeny are included, which support Nakai's view. In addition, Nakato (1987), after making a chromosome count of the Japanese species, divided them into two groups, one corresponding to _Spicantopsis_ with x = 31 and the other to _Struthiopteris_ with x = 34.  This proposal was already accepted in TPG (2019) and has been used in posterior publications (eg. Ebihara & Nitta, 2019;  Molino et al., 2020; Testo et al., 2022,  Ebihara et al., 2023).
The genus is now conceived with the following species:
_Spicantopsis amabilis_ (Makino) Nakai
_Spicantopsis hancockii_ (Hance) Masam.
_Spicantopsis niponica_ (Kunze) Nakai

### Reference(s) for publication of the name

Ebihara, A., Tagane, S., Hirota, S.K., Suyama, Y., Nakato, N. & Kuo, L.-Y. 2023. Resurrection of _Spicantopsis hancockii_ (Blechnaceae) as an endemic species to Taiwan – Reidentification of _Spicantopsis_ in the Tokara Islands, Japan. Taiwania 68(2): 148-154.
Ebihara, A., & Nitta, J.H. 2019. An update and reassessment of fern and lycophyte diversity data in the Japanese Archipelago. Journal of plant research, 132(6), 723-738.
Gasper, A., Almeida, T., Dittrich, V., Smith, A. & Salino, A. 2017. Molecular phylogeny of the fern family Blechnaceae (Polypodiales) with a revised genus-level treatment. Cladistics, 33: 429–476.
Gasper, A., Almeida, T., Dittrich, V., Smith, A. & Salino, A. 2016. A classification for Blechnaceae (Polypodiales: Polypodiopsida): New genera, resurrected names, and combinations. Phytotaxa, 275(3): 191-227.
Molino, S., Gabriel y Galán, J.M., Prada, C., Estébanez, B., Vázquez, R. & Wasowicz, P. 2020. Sporangia and spores in the fern genera _Struthiopteris_ and _Spicantopsis_ (Blechnaceae, Polypodiopsida). Botanical Review 86: 76‒92.
Molino, S., Gabriel y Galán, J.M., Sessa, E.B. & Wasowicz, P.. 2019. A multi-character review of Struthiopteris leads to the rescue of _Spicantopsis_ (Blechnaceae, Polypodiopsida). Taxon. 68(2): 185-198.
Nakai, T. 1933. Notes on Japanese ferns IX. The Botanical Magazine of Tokyo. 47(555): 180-186.
PPG I 2016. A community-derived classification for extant lycophytes and ferns. Journal of Systematics and Evolution. 54: 563-603.
Testo, W. L., de Gasper, A. L., Molino, S., Galán, J. M. G. Y., Salino, A., Dittrich, V. A. D. O., & Sessa, E. B. 2022. Deep vicariance and frequent transoceanic dispersal shape the evolutionary history of a globally distributed fern family. American Journal of Botany, 109(10), 1579-1595.
Tagawa, M. 1952. Occasional Notes on Asiatic Pteridophytes 3. Acta Phytotaxonomica et Geobotanica, 14(6): 191-194.
TPG. 2019. Updating Taiwanese pteridophyte checklist: a new phylogenetic classification. Taiwania 64(4): 367-195.

### List the numbers of any related issues

#12

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 2 (voting period August 2023). A total of 70 votes were cast. There were 67 'Yes' votes (95.7%) and 3 'No' votes (4.3%). The proposal passes.

**Comment by joelnitta** [comment]
Already implemented in data, closing.
