### ISSUE TITLE
Recognition of Sahashia (Ophioglossaceae) [PASSED]

### ISSUE THREAD

**Issue by choess** [pteridogroup/ppg#14]
### Name of taxon

Sahashia

### Rank of taxon

Genus

### Approximate number of species affected

1

### Description of change

Recognize _Sahashia_ Li Bing Zhang & Liang Zhang as a segregate genus from _Botrypus_ Michx. sensu PPG I.

### Reason for change

The PPG I circumscription of _Botrypus_ Michx. was recognized as non-monophyletic based on Hauk et al. 2003 and Shinohara et al. 2013, which showed the two species placed there (_B. strictus_ (Underw.) Holub and _B. virginianus_ (L.) Michx.) forming a grade at the base of Botrychoideae, with _B. strictus_ sister to the rest of the subfamily.

Zhang et al. 2020 described the new genus _Sahashia_ to accommodate the former _B. strictus_ and make _Botrypus_ (now containing one cryptically diverse species) monophyletic.

_Botrypus_ sensu PPG I could be distinguished from the other genera of Botrychioideae by the site of the junction between sporophore and trophophore (at the base of the sporophore lamina, sharing a common stipe in _Botrypus_ s.l. vs at or near ground level for _Sceptridium_ and above the base of the lamina in _Japanobotrych(i)um_) and the degree of division of the trophophore (generally tri- to tetrapinnate in _Botrypus_ s.l. vs. not more than bipinnate in _Botrychium_ s.s.). Zhang et al. suggest further distinguishing _Sahashia_ from _Botrypus_ s.s. by its narrow, linear sporophore (vs. deltate in the latter); other characters are given in couplet 6 of the [Flora of China _Botrychium_ treatment](http://efloras.org/florataxon.aspx?flora_id=2&taxon_id=104332).

This proposal resolves the lack of monophyly noted in PPG I, which is desirable. The five clades here proposed as genera are readily distinguishable from one another on the basis of gross morphology and certainly deserve formal rank. Rank at genus level is most consistent with the treatment established in PPG I. The principal alternative would be to treat all five genera in Botrychioideae as a broadly circumscribed _Botrychium_, for which there is historical precedent. Were this course followed, a new combination ought to be made for _Sahashia_ as a subgenus of _Botrychium_ s.l.

Hauk WD, Parks CR, Chase MW. 2003. Phylogenetic studies of Ophioglossaceae: Evidence from rbcL and trnL-F plastid DNA sequences and morphology. Molecular Phylogenetics and Evolution 28: 131–151. [https://doi.org/10.1016/S1055-7903(03)00032-0](https://doi.org/10.1016/S1055-7903(03)00032-0)

Shinohara W, Nakato N, Yatabe-Kakugawa Y, Oka T, Kim JK, Murakami N, Noda H, Sahashi N. 2013. The use of matK in Ophioglossaceae phylogeny and the determination of Mankyua chromosome number shed light on chromosome number evolution in Ophioglossaceae. Systematic Botany 38: 564–570. [https://doi.org/10.1600/036364413X670232](https://doi.org/10.1600/036364413X670232)

Liang Zhang, Xue-Ping Fan, Sahanat Petchsri, Lin Zhou, Rossarin Pollawatn, Xin Zhang, Xin-Mao Zhou, Ngan Thi Lu, Ralf Knapp, Sahut Chantanaorrapint, Ponpipat Limpanasittichai, Hang Sun, Xin-Fen Gao, Li-Bing Zhang. 2020. Evolutionary relationships of the ancient fern lineage the adder's tongues (Ophioglossaceae) with description of Sahashia gen. nov. Cladistics 36(4): 380–393. [https://doi.org/10.1111/cla.12408](https://doi.org/10.1111/cla.12408)

### Reference(s) for publication of the name

Liang Zhang, Xue-Ping Fan, Sahanat Petchsri, Lin Zhou, Rossarin Pollawatn, Xin Zhang, Xin-Mao Zhou, Ngan Thi Lu, Ralf Knapp, Sahut Chantanaorrapint, Ponpipat Limpanasittichai, Hang Sun, Xin-Fen Gao, Li-Bing Zhang. 2020. Evolutionary relationships of the ancient fern lineage the adder's tongues (Ophioglossaceae) with description of Sahashia gen. nov. Cladistics 36(4): 380-393. [https://doi.org/10.1111/cla.12408](https://doi.org/10.1111/cla.12408)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by Ben999999** [comment]
It makes sense to recognise Sahashia as a new genus according to morphological and molecular data / analyses presented in Zhang et al. 2020.

**Comment by WDHauk23** [comment]
I support this proposal. I think it makes no sense to have such a diverse array of morphological variation contained in a single genus. Recognizing _Sahashia_ resolves the non-monophyletic status of _Botrypus_, which has been supported by several independent investigations.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 2 (voting period August 2023). A total of 65 votes were cast. There were 58 'Yes' votes (89.2%) and 7 'No' votes (10.8%). The proposal passes.

**Comment by joelnitta** [comment]
Already implemented in data, closing.
