### ISSUE TITLE
Recognition of Rouxopteris (Gleicheniaceae) [PASSED]

### ISSUE THREAD

**Issue by choess** [pteridogroup/ppg#15]
### Name of taxon

Rouxopteris

### Rank of taxon

Genus

### Approximate number of species affected

1

### Description of change

Recognize _Rouxopteris_ Hong M.Liu as a segregate genus from _Gleichenia_ Sm.

### Reason for change

When recognized in PPG I, _Gleichenia_ Sm. was thought to be monophyletic, but limited phylogenetic sampling was available. Liu et al. 2020 undertook a phylogenetic analysis including the Malagasy-Mascarene species _Gleichenia boryi_ Kunze, which was determined to be an isolated lineage not forming a clade with the remainder of _Gleichenia_. As it lacks close relatives, Liu et al. erected a new genus, _Rouxopteris_, to contain it and maintain the monophyly of _Gleichenia_.

While the ultimate segments have the narrow deeply-lobed appearance of those in _Gleichenia_ s.s., _Rouxopteris boryi_ lacks the pseudodichotomous branching characteristic of the family (except for _Stromatopteris_). The bi-pinnatifid leaves lacking a dormant terminal bud and pseudodichotomous branching serve to distinguish it from _Gleichenia_ s.s.

It would be difficult to find an alternative to recognizing _Rouxopteris_ that would maintain monophyletic genera in Gleicheniaceae. Liu et al. found it to be sister to a _Diplopterygium_-_Gleichenella_-_Dicranopteris_ clade but this relationship was not strongly supported. Trying to circumscribe a genus in Gleicheniaceae which could include _Rouxopteris_ as a basal morphologically aberrant member would require merging other existing genera with recognizable and more or less stable circumscriptions.

### Reference(s) for publication of the name

H Liu, F Rakotondrainibe, S Hennequin, H Schneider. (2020) The significance of Rouxopteris (Gleicheniaceae, Polypodiopsida):
a new genus endemic to the Madagascan region. Plant Systematics and Evolution 306(2, 30)
[https://doi.org/10.1007/s00606-020-01657-9](https://doi.org/10.1007/s00606-020-01657-9)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 2 (voting period August 2023). A total of 69 votes were cast. There were 67 'Yes' votes (97.1%) and 2 'No' votes (2.9%). The proposal passes.

**Comment by joelnitta** [comment]
Already implemented in data, closing.
