### ISSUE TITLE
Recognition of Adetogramma (Polypodiaceae) [PASSED]

### ISSUE THREAD

**Issue by Blotiella** [pteridogroup/ppg#17]
### Name of taxon

Adetogramma T.E.Almeida

### Rank of taxon

Genus

### Approximate number of species affected

1

### Description of change

_Adetogramma_, a monotypic genus in Polypodiaceae, was described by Almeida et al. (2017) to accommodate _Polypodium chrysolepis_ Hook. The species had been previously combined in _Microgramna_ (_Microgramma chrysolepis_(Hook.) Crabbe).

### Reason for change

Phylogenetic inferences by Schneider et al. (2004) indicated that _Polypodium chrysolepis_ was not related to _Microgramma_. Later phylogenetic and morphological evidence showed that _Polypodium chrysolepis_ constitutes an isolated lineage among the neotropical polygrammoid ferns, close to _Serpocaulon_ and the grammitids (Almeida et al. 2017). The results were later supported by the phylogenomic inference of Wei and Zhang (2022).
 _Adetogramma_ can be distinguished by its entire leaves with free veins and peltate, pedicellate, and lanceolate paraphyses. It can be distinguished from _Microgramma_, by the anastomosing veins on the sterile fronds of the latter (vs. free veins in _Adetogramma_). Moreover, _A. chrysolepis_ has lanceolate, peltate, long-stalked paraphyses while in _Microgramma_, paraphyses (if present) are hairlike or lanceolate and sessile, never stalked. 
_Adetogramma_ can be readily distinguished from _Serpocaulon_ by having free veins, non-clathrate scales, peltate scales covering the laminar surfaces, and peltate scales as paraphyses. These characers contrast with features of Serpocaulon species: regular anastomosing veins (goniophlebioid venation), clathrate scales, and the absence of scales in veins or laminar surface between veins or paraphyses, or if paraphyses are present, they are 2-3 celled glands.
_Adetogramma_ also resembles some _Pleopeltis_ species in having entire laminae, long-creeping rhizomes, and peltate paraphyses. The main difference between _Pleopeltis_ and _Adetogramma chrysolepis_ lies in the shape of the paraphyses – ovate-lanceolate in _Adetogramma_ vs. roundish in _Pleopeltis_. Furthermore, species of _Pleopeltis_ with entire blades always have anastomosing veins.
_Polypodium_ s.s. can be distinguished from _A. chrysolepis_ by its deeply-pinnatifid to pinnate leaves with free (in the Polypodium dulce complex species) to anastomosing veins, with a single included veinlet in each areole. Indument is also a useful character for separating _A. chrysolepis_, as _Polypodium_ _s.s._ shows glabrous to pilose laminar surfaces and the paraphyses, when present, are filamentous or branched, while _Adetogramma_ has scaly laminae and the paraphyses are pedicellate scales.

### Reference(s) for publication of the name

Almeida TE, Salino A, Dubuisson J, Hennequin S. 2017. _Adetogramma_ (Polypodiaceae), a new monotypic fern genus segregated from _Polypodium_. PhytoKeys 78: 109–131. DOI: 10.3897/phytokeys.78.12189

Crabbe JA. 1967. Bolivian pteridophytes collected by Winifred Brooke. Fern Gazette 9: 309–320.

Schneider H, Smith AR, Cranfill R, Hildebrand TJ, Haufler CH, Ranker TA. 2004. Unraveling the phylogeny of polygrammoid ferns (Polypodiaceae and Grammitidaceae): exploring aspects of the diversification of epiphytic plants. Molecular Phylogenetics and Evolution
31(3): 1041–1063. DOI: 10.1016/j.ympev.2003.09.018

Wei R, Zhang X-C. 2022. A revised subfamilial classification of Polypodiaceae based on plastome, nuclear ribosomal, and morphological evidence. Taxon 71(2): 288-306. DOI: 10.1002/tax.12658

[Almeida_et_al_2017_Adetogramma.pdf](https://github.com/pteridogroup/ppg/files/11790055/Almeida_et_al_2017_Adetogramma.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 2 (voting period August 2023). A total of 69 votes were cast. There were 67 'Yes' votes (97.1%) and 2 'No' votes (2.9%). The proposal passes.

**Comment by joelnitta** [comment]
Already implemented in data, closing.
