### ISSUE TITLE
Tribes or sub-families?

### ISSUE THREAD

**Issue by schwartsburd** [pteridogroup/ppg#22]
### Name of taxon

Several

### Rank of taxon

Tribe

### Approximate number of species affected

none

### Description of change

As pointed out by the International Code of Nomenclature (Art. 4.1), the main and natural secondary rank between a Family and a Genus is a Tribe. On article 4.2, there is a further option to include third ranks, using the prefix "sub-". Therefore between Family and Genus, we have: Family, sub-Family, Tribe, sub-Tribe, Genus.
Note 1 of the Code says it is not mandatory to follow this classification.
I understand that sub-Family has been largely used in the Systematics of ferns, but not always. Tryon & Tryon (Ferns, allied pl. 1982), for example, adopted the use of Tribes instead of sub-Families.
Since we are using only one rank between Family and Genus, for me is more logical to adopt Tribe instead of sub-Family. 
I also propose we use Tribes (or sub-Families) only to those bigger Families, such as Pteridaceae, Dryopteridaceae, Polypodiaceae, etc., similar to PPG I - even though I myself used sub-Families of Dennstaedtiaceae in a paper, for the sake of discussion, and not classification.
In addition, Tribes are easier speakable compared to sub-Families: Grammitideae versus Grammitidoideae; Polypodieae versus Polypodioideae.
I realize this proposal will be itching.

### Reason for change

See above in the description.

### Reference(s) for publication of the name

Tryon, R.M. & Tryon, A.F. 1982. Ferns and allied plants with special reference ro Tropical America. Springer-Verlag, New York.

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by choess** [comment]
This is a very interesting point. How well is this respected in modern seed plant taxonomy? Off the top of my head, the groups in which I can think of tribes being used are ones with a "full stack" (subfamilies, tribes, subtribes) of ranks being used between family and genus, such as Orchidaceae, Poaceae, Asteraceae, Apocynaceae and perhaps Apiaceae.

**Comment by joelnitta** [comment]
Thanks for raising this idea @schwartsburd.

However, for taxonomic proposals, [we require](https://pteridogroup.github.io/guidelines.html) that you provide a validly published reference **for each name**. So you would need to provide a valid reference for each of the tribes to be recognized instead of subfamilies.

Otherwise, this would be more appropriate as a general discussion, and should be moved to the [discussion board](https://github.com/pteridogroup/ppg/discussions).

**Comment by schwartsburd** [comment]
Dear @joelnitta thanks for alerting me. I'll move this to the Discussion board.

**Comment by joelnitta** [comment]
Thanks @schwartsburd! Posting a link so others can find it: https://github.com/pteridogroup/ppg/discussions/23
