### ISSUE TITLE
Recognition of Zealandia (Polypodiaceae) [NOT PASSED]

### ISSUE THREAD

**Issue by DrAshleyField** [pteridogroup/ppg#26]
### Author(s) of proposal

Ashley Field

### Name of taxon

Zealandia Testo & A.R.Field

### Rank of taxon

Genus

### Approximate number of species affected

3

### Description of change

[Testo et al. (2019)](https://doi.org/10.1600/036364419X15650157948607) described the genus _Zealandia_ Testo & A.R.Field based on a molecular phylogenetic and morphological appraisal as part of a multi-genus approach to achieving monophyly from a previously paraphyletic _Microsorum_ and _Colysis_. The abstract of Testo et al. (2019)  is reproduced below:

"The taxonomy of the Polypodiaceae subfamily Microsoroideae is highly problematic, especially with respect to the circumscription of the highly variable and non-monophyletic genus _Microsorum_. Using phylogenetic analyses and morphological evidence, we demonstrate that sixteen taxa typically treated in the genera _Microsorum_ and _Colysis_ are not closely related to those groups and instead belong to three clades that are successive sister groups to the Old-World ant-fern genus, _Lecanopteris_. We use the available genus name Dendroconche for one of these clades and propose the new genera _Bosmania_ and _Zealandia_ to accommodate the remaining two groups. We provide a description and identify morphological synapomorphies for each of the genera, make new combinations and designate lectotypes where necessary, and present keys and descriptions for all relevant species. We also discuss the evolution of ant-fern associations in the lecanopteroid ferns and highlight the need for additional taxonomic work in the subfamily. The following new combinations are provided: _Bosmania lastii, B . leandriana, B . membranacea, Dendroconche ampla, D . latilobata, D . linguiforme, D . sayeri, D . scandens, D . varians, Zealandia novae-zealandiae, Z . powellii, Z . pustulata, Z . pustulata_  subsp. _howensis_, and _Z . vieillardii_."

### Reason for change

Multiple studies have shown that _Microsorum_ and _Colysis_ as adopted in PPG I (2016) were paraphyletic. This proposal is directed at achieving monophyly among relevant genera by recognition of three separate new genera for the clades presented by [Testo et al. (2019)](https://doi.org/10.1600/036364419X15650157948607) and also presented by [Chen et al. (2020)](https://doi.org/10.1016/j.ympev.2019.106665). This proposal should be read in conjunction with proposals for  _Bosmania_ + _Dendroconche_ + _Lecanopteris_ s.s. sensu  [Testo et al. (2019)](https://doi.org/10.1600/036364419X15650157948607) (#25, #27).

This proposal affects species occurring primarily in Australia, New Caledonia and New Zealand. It was adopted by [Australian Plant Census](https://biodiversity.org.au/nsl/services/rest/instance/apni/51445013) but not for the [New Zealand Fern Flora](https://www.nzflora.info/factsheet/Taxon/Lecanopteris.html). It has been superseded in [World Ferns](https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list#plantUid-9359).

An alternative classification to achieve monophyly was presented by [Perrie et al. (2021)](https://doi.org/10.3767/blumea.2021.66.03.07) by expanding the circumscription of _Lecanopteris_. This alternative affects the same number of taxa overall, and should be examined in the alternative PPG II proposals for _Bosmania_ + _Lecanopteris_ s.l. sensu [Perrie et al. (2021)](https://doi.org/10.3767/blumea.2021.66.03.07) (#28).

### Reference(s) for publication of the name

Testo W.L., Field A.R., Sessa E.B., Sundue M. (2019) Phylogenetic and Morphological Analyses Support the Resurrection of Dendroconche and the Recognition of Two New Genera in Polypodiaceae Subfamily Microsoroideae Systematic Botany 44(4): 1–16.

See also:

Chen C-C, Hyvönen J, Schneider H. 2020. Exploring phylogeny of the microsoroid ferns (Polypodiaceae) based on six plastid DNA markers. Molecular Phylogenetics and Evolution 143: 106665.

Field A.R. (2020) Classification and typification of Australian lycophytes and ferns based on Pteridophyte Phylogeny Group classification PPG I. Australian Systematic Botany 33(1): 1–102.

Perrie L.R., Field A.R., Ohlsen D.J., Brownsey P.J. (2021) Expansion of the fern genus Lecanopteris to encompass some species previously included in Microsorum and Colysis (Polypodiaceae) Blumea 66: 242–248.

### List the numbers of any related issues

#25, #27, #28

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 3 (voting period September 2023). A total of 67 votes were cast. There were 43 'Yes' votes (64.2%) and 24 'No' votes (35.8%). The proposal does not pass.
