### ISSUE TITLE
Rejection of Ellipinema (Polypodiaceae, Polypodiopsida)

### ISSUE THREAD

**Issue by weiran007** [pteridogroup/ppg#36]
### Author(s) of proposal

Ran Wei

### Name of taxon

Ellipinema and Lepisorus

### Rank of taxon

Genus

### Description of change

Rejection of Ellipinema to keep Lepisorus monophyletic.

### Reason for change

According to molecular evidence of nuclear markers, Ellipinema and allied genera, such as Lepidomicrosorium, Lemmaphyllum, Neolepisorus, Paragramma, Tricholepidium and Weatherbya are deeply nested within Lepisorus. The nuclear phylogeny showing incongruent phylogenetic placement in comparison with plastid results perhaps indicated ancient hybridization events. The diagnostic morphology characterizing Ellipinema – elliptic scale-like paraphyses, which is shared by all the taxa of sect. Lepisorus and sect. Hymenophyton – falls within the range of continuous variation in the type species Lepisorus jakonensis.

### Reference(s) for publication of the name

Wei R, Zhao CF, Xiang QP, Zhang XC. 2021. Ellipinema and ×Ellipisorus? Just Lepisorus (Polypodiaceae)! Molecular Phylogenetics and Evolution, 161: 107176.
Zhao CF, Wei R, Zhang XC, Xiang QP. 2020. Backbone phylogeny of Lepisorus (Polypodiaceae) and a novel infrageneric classification based on the total evidence from plastid and morphological data. Cladistics, 36: 235-258.

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by choess** [comment]
Technically, I think this proposal as written is unnecessary--_Ellipinema_ was not recognized in PPG I so it would not be recognized in PPG II without an explicit proposal to do so. From reading Zhao et al. 2020, it looks as though _Lemmaphyllum_, _Lepidomicrosorium_, _Neocheiropteris_, _Neolepisorus_, _Paragramma_, and _Tricholepidium_, all recognized in PPG I, should be proposed for submersion in a broadly-construed _Lepisorus_ in PPG II.

**Comment by joelnitta** [comment]
Thanks for catching that @choess. You are correct - this proposal is not valid since it does not change anything from PPG I, so I am closing it. I have added a row (number 69) for consolidation of various segregates into Lepisorus in the ["to-do" sheet](https://docs.google.com/spreadsheets/d/17pWet-jbCsKivPhl6FlDw9AheBcP5eKDxNahl7obUsw/edit#gid=0).

**Comment by joelnitta** [comment]
@weiran007 I just want to draw your attention to a related, recently submitted proposal to recognize *Ellipnema*, #46. If you indeed want to recognize a broadly-construed *Lepisorus* including *Ellipnema* and the other segregate genera, you would need to submit a proposal to that effect.

**Comment by weiran007** [comment]
> @weiran007 I just want to draw your attention to a related, recently submitted proposal to recognize _Ellipnema_, #46. If you indeed want to recognize a broadly-construed _Lepisorus_ including _Ellipnema_ and the other segregate genera, you would need to submit a proposal to that effect.

#joelnitta Hi, Dr. Nitta, thank you so much for your reminder and suggestion. So I will try to submit a new proposal for recoginzing a broadly defined Lepisorus sensu lato.
