### ISSUE TITLE
The generic circumscription of Cheilanthes Sw. (Cheilanthoideae, Pteridaceae) [NOT PASSED]

### ISSUE THREAD

**Issue by MoniPonce** [pteridogroup/ppg#39]
### Author(s) of proposal

M. M. Ponce and M. A. Scataglini

### Name of taxon

Cheilanthes Sw.

### Rank of taxon

Genus

### Approximate number of species affected

70

### Description of change

From a total of about 100 species of _Cheilanthes_ s.l. , in PPG I (2016), ca. 70 of them would belong to the s. str. clade, distributed in South America, Australasia, Africa, and Madagascar.
In our recent studies (Ponce & Scataglini, 2020), in order to examine the phylogenetic position of _Cheilanthes_ species from South America, we reconstructed a representative molecular phylogeny of the hemionitioid clade. As a result, from a total of ca. 35 South American _Cheilanthes_ species, more than 20 of them appeared in the _Cheilanthes_ s. str. clade with maximum support. We propose that the _Cheilanthes_ s. str. clade contains three subclades: 1) exclusively South American species (≈10 spp.), 2) Australasia + ≈16 South American species, including the type _C. micropteris_, and 3) exclusively African and Madagascar species. Recently, _Cheilanthes volcanensis_ de la Sota, a poorly known species restricted to North-western Argentina and Bolivia, was also confirmed in the exclusive South America clade (Ponce et al. 2023).
On the other hand, three _Cheilanthes_ species (_C. geraniifolia, C. goyazensis_ and _C. bradei_) from Northern, Central Western and South Eastern Brazil, appear segregated from the _Cheilanthes_ s. str. clade in our phylogeny. These three species plus two morphologically related taxa, _C. eriophora_ and _C. steyermarkii_, were transferred to the new genus _Mineirella_ Ponce & Scataglini (2020). (see _Mineirella_ proposal)

### Reason for change

The hemionitioid group is composed of three highly supported main clades: 1) _Cheilanthes_ s. str., 2) _Hemionitis_ clade + “Pellaeopsis” group (from Africa and Madagascar), and 3) _Adiantopsis_ – _Doryopteris_ clade, which also include neotropical (e.g. _Mineirella_) and paleotropical (e.g. _Choristosoria_) species groups. The relationships between these three main clades were showed in previous works but they have not been fully resolved yet (Eisenhardt et al. 2011; Yesilyurt et al. 2015, Ponce & Scataglini, 2018; 2020).
The _Cheilanthes_ s. str. is morphologically heterogeneous, but presents diagnostic characters that difference it from the remaining cheilantoids ferns : concolor rhizomatic scales (vs. bicolor rhizomatic scales in _Adiantopsis_, _Doryopteris_, _Mineirella_); free veins, apically widened (vs. not or slightly widened vein tips in _Myriopteris_), sporangia at the vein tips (vs. along the veins in _Hemionitis_); elongated cordiform or ribbon like, glabrous gametophytes (vs. pilose gametophytes in _Hemionitis_, and farinose glandular gametophytes in _Notholaena_). Root anatomy with whole cortex thinned cell walls or gradually thickened cell walls and wide lumen (vs. inner cortex with strongly thickened cell walls and narrow lumen in _Adiantopsis, Doryopteris_ and _Mineirella_) (cfr. Hernández, 2019 Thesis). Also, the Australasian-South American _Cheilanthes_ subclade presents exclusively 32 small spores per sporangium, in sexual condition (vs. 64 small spores per sporangium in sexual condition, present in most of the cheilanthoids species) (cfr. Gruzs & Windham, 2013; Ponce & Scataglini, 2018, 2020).

### Reference(s) for publication of the name

Ponce, M. Mónica, and M. Amalia Scataglini. 2018. “Further Progress towards the Delimitation of Cheilanthes (Cheilanthoideae, Pteridaceae), with Emphasis on South American Species.” Organisms Diversity & Evolution 18 (2): 175–86. https://doi.org/10.1007/s13127-018-0366-6.
 [Ponce & Scataglini_Further progress towards the delimitation of Cheilanthes_ODAE2018.pdf](https://github.com/pteridogroup/ppg/files/12422803/Ponce.Scataglini_Further.progress.towards.the.delimitation.of.Cheilanthes_ODAE2018.pdf)

Ponce, Marta Mónica, and María Amalia Scataglini. 2022. “Phylogenetic Position of South American Cheilanthes (Cheilanthoideae, Pteridaceae): Advances in the Generic Circumscription and Segregation of the New Genus Mineirella.” Journal of Systematics and Evolution 60 (2): 266–80. https://doi.org/10.1111/jse.12723.
 [Ponce & Scataglini_Phylogeny of Cheilanthes .pdf](https://github.com/pteridogroup/ppg/files/12422807/Ponce.Scataglini_Phylogeny.of.Cheilanthes.pdf)

Ponce, M. Mónica, M. Amalia Scataglini, Marcela A. Hernández, and Olga G. Martínez. 2023. “Análisis Moleculares y Observaciones Morfo-Anatómicas de Cheilanthes Volcanensis (Pteridaceae) Definen Sus Relaciones Dentro de La Subfamilia Cheilanthoideae En Sudamérica.” Darwiniana, Nueva Serie 11 (1): 101–14. https://doi.org/10.14522/darwiniana.2023.111.1118.
 [Ponce et al_Cheilanthes volcanensis_DWN2023.pdf](https://github.com/pteridogroup/ppg/files/12422810/Ponce.et.al_Cheilanthes.volcanensis_DWN2023.pdf)

### List the numbers of any related issues

#40 

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by crothfels** [comment]
The cheilanthoid ferns are one of the most glaring (the most glaring?) areas of phylogenetic/taxonomic/nomenclatural uncertainty in PPG 1, and this proposal looks to me to be a good step forward. However, I know that Michael Windham, Kathleen Pryer, Eric Schuettpelz, and collaborators have been working on the phylogenetics and taxonomy of the hemionitids for a long time and will publish their results soon (I hope ;-) ). I'm not sure if this proposal fits with their results and proposed taxonomy or not, but perhaps some coordination with that group would be useful at this stage?

**Comment by gyatskievych** [comment]
I think that any proposal that wishes to limit the circumscription of a genus should account for the generic placement of all of the excluded species.  Otherwise, PPG II will wind up with an excessively large insertae sedis list. To that extent, I think that this proposal may be premature.

**Comment by joelnitta** [comment]
@MoniPonce could you clarify **how** this will change the generic circumscription of *Cheilanthes*, in particular how it differs from that in PPG I? It seems you are proposing to narrow the circumscription to only the s.s. clade, correct?

**Comment by joelnitta** [comment]
@MoniPonce also, in your proposal you mention "Ponce & Scataglini, 2020", but I think this should be 2022? (please note I updated the formatting of the references).

**Comment by MoniPonce** [comment]
In our study, we found strong support for Cheilanthes s.s. being composed of the following clades: (i) the clade of Australasian + C. micropteris (now, plus C. ecuadoriensis) together with ten South American species, (ii) the clade formed by ca. 25 African Cheilanthes species (Eiserhardt et al., 2011), and (iii) the exclusively South American Cheilanthes clade that includes ten species. According to these results, we propose to recognize Cheilanthes s.s. as a genus that includes three geographical groups: a South American–Australasian clade with 32 spores per sporangium species, and an African and an exclusively South American clade, both with 64 spores per sporangium species.
Globally, the Cheilanthes is a circum-austral genus that comprises about 70 species, based on phylogeny and morphological similarities, with ca. 30 species in South America (Ponce & Scataglini, 2020 [2022], 2023), ca. 25 species in Africa (Eiserhardt et al., 2011), and about 15 species in Australasia (Quirk et al., 1983).
Regarding the delimitation of the strict sense of Cheilanthes, we largely agree with the classification system proposed in World Ferns (https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list#1696276375). In this list, the taxa incertae sedis are significantly reduced compared to the number of names assigned to Cheilanthes. In this system, the majority of cheilanthoid taxa are located in morphologically fairly well circumscribed genera whose monophyly would have to be adjusted by sequencing a larger sample of the Eurasia Cheilanthes s.l. species, that mostly belonging to genera Aleuritopteris (Zhang et al., 2007, 2013) and Oeosporangium (Fraser‐Jenkins, 2016; Fraser‐Jenkins et al., 2017), but their phylogenetic position must be corroborated.
Furthermore, we obtained well support for two groups of species belonging to Cheilanthes, Doryopteris and Pellaea from Africa and Madagascar that should be transferred to the genera Pellaeopsis J. Sm. and Choristosoria Mett. ex Kuhn. These assignments would improve the generic limits. This would not be an obstacle to review the delimitation range of each of the species of these genera. Consequently, if there is consensus to restore the old names, new combinations would be necessary for several Choristosoria and Pallaeopsis species names.

Moreover, the circumscription of Cheilanthes s.s. and the new genus Mineirella were actually published in the JSE online version of December 2020, and in the printed version of 2022. See IPNI (https://www.ipni.org/?q=Mineirella) and World ferns (https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list#plantUid-5510)
**Ponce, M. M. & M. A. Scataglini 2020 [2022]. Phylogenetic position of South American Cheilanthes (Cheilanthoideae, Pteridaceae): Advances in the generic circumscription and segregation of the new genus Mineirella. Journal of Systematics and Evolution 60(2): 266-280. doi: 10.1111/jse.12723.**

**Comment by tomaranker** [comment]
You state that the gametophytes of Hemionitis species are pilose. The gametophytes that I have grown of H. levyi and H. palmata are glabrous. See attached. I may have higher resolution files if I can find them.
![H levyi gametophyte](https://github.com/pteridogroup/ppg/assets/126416927/6c4914ba-df68-44d8-bd01-37788db1740f)
![H palmata gametophyte](https://github.com/pteridogroup/ppg/assets/126416927/07345447-2c43-473a-a910-6d13cb9a47a3)

**Comment by tomaranker** [comment]
The gametophyte photos may show up better in this pdf slide.
[gpt symmetry.pdf](https://github.com/pteridogroup/ppg/files/12850367/gpt.symmetry.pdf)

**Comment by MoniPonce** [comment]
Debí decir Hemionitis tomentosa. Adjunto foto.
Gracias por las fotos de las otras especies de Hemionitis.

**Comment by crothfels** [comment]
I want to echo @gyatskievych 's comment. I think the referenced papers are very useful for refining our understanding of relationships within the hemionitid clade, and ultimately for informing our understanding of the circumscription of Cheilanthes. And I personally am in favor of the proposed segregates here --Minierella etc. But we are still a ways from having a useful monophyletic Cheilanthes. The circumscription proposed here leaves lots of taxa orphaned--there are a bunch of species that we know are not members of the "Cheilanthes s.str." clade proposed here but which do not have another genus available. So we're still stuck with a non-monophyletic Cheilanthes and thus this proposal doesn't bring us forward (in the specific sense of the circumscription of Cheilanthes). Again, I think recognizing the proposed segregates is useful but a monophyletic Cheilanthes itself is still out of reach.

**Comment by MoniPonce** [comment]
The list of 74 _Cheilanthes_ species shown here, based on https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list, includes 56 species confirmed within the genus, using molecular or reproductive data. The remaining 18 species would be putative _Cheilanthes_ but will need to be tested to confirm this.
All other_Cheilanthes_ species not included in this list have already been assigned to other genera and/or the phylogenetic analyses showed them distant from the _Cheilanthes_ s str. clade.

[Tentative list of Cheilanthes s. str. species.docx](https://github.com/pteridogroup/ppg/files/13182998/Tentative.list.of.Cheilanthes.s.str.species.docx)

[List of 18 incertae sedis Cheilanthes species.docx](https://github.com/pteridogroup/ppg/files/13183001/List.of.18.incertae.sedis.Cheilanthes.species.docx)

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 4 (voting period October 2023). A total of 52 votes were cast. There were 25 'Yes' votes (48.1%) and 27 'No' votes (51.9%). The proposal does not pass.
