### ISSUE TITLE
Recovery of Pellaeopsis (Pteridaceae)

### ISSUE THREAD

**Issue by MoniPonce** [pteridogroup/ppg#41]
### Author(s) of proposal

M. M. Ponce and M. A. Scataglini

### Name of taxon

Pellaeopsis J. Sm. 

### Rank of taxon

Genus

### Approximate number of species affected

Ten

### Description of change

Ten species from Africa and Madagascar, usually assigned to _Cheilanthes_ s.l., _Doryopteris_ s.l. and _Pellaea_ s.l., would correspond to _Pellaeopsis_ J. Sm. (1875), an ancient paleotropical genus that need to be recovered and redefined.

### Reason for change

In our phylogenetic reconstruction of cheilanthoid ferns to delimit _Cheilanthes_ s.s. (Ponce & Scataglini 2020), we include paleotropical incertae sedis species, usually assigned to _Cheilanthes_ s.l, _Doryopteris_ s.l. and _Pellaea_ s.l. We obtained a 100% supported clade, sister to genus _Hemionitis_, made up of _Cheilanthes leachii, Doryopteris pilosa, D. pedatoides, Pellaea angulosa, P. boivinii, P. doniana, P. dura, P. longipilosa, P. maxima_ and _P. pectiniformis._ This clade would correspond to the genus _Pellaeopsis_ Smith, 1875 ≡ _Pteridella_ Mett. ex Kuhn, 1879. Smith defined _Pellaeopsis_ composed by _P. burkeana_ ≡ _P. dura_ and _P. angulosa_ ≡ _P. articulata_, the later as the type species, while Kuhn included eight species under _Pteridella_ with _P. doniana_ as the type species.
We adopt to this group the name with priority, _Pellaeopsis_.
The ten species clustered in our phylogeny differ from _Cheilanthes_ s.s. by their laminae more or less coriaceous, glabrous or with squamiformis hairs; ultimate segments articulated; venation partially anastomosing or free (vs. laminae herbaceous, sometime subcarnosus, with glandular or simples hairs, ultimate segments no articulated, venation free); from _Doryopteris_ s.s. by their rhizome scales non-clathrate, linear-lanceolate or triangular-lanceolate (vs. scales of rhizome and petiole bases clathrate, more or less ovate-lanceolate); tuberculate, granulose or rugulose perispore (vs. predominantly cristate- reticulate perispore, sometime rugulate spores); and from _Pellaea_ s.s., by their laminae usually pedate-pinnatifid up to pedate-4-pinnate, having the basal basiscopic portions of the basal pinnae more developed or divided, (vs. pinnate up to 3-pinnate); 4-furcate or partially anastomosed veins (vs. 2-3-furcate free veins); sligthly recurved, narrow, membranous  indusium (vs. usually strongly revolute, thickened indusium).

### Reference(s) for publication of the name

[Kirkpatrick_Pellaea-2007.pdf](https://github.com/pteridogroup/ppg/files/12423507/Kirkpatrick_Pellaea-2007.pdf)
[Ponce & Scataglini_Further progress towards the delimitation of Cheilanthes_ODAE2018.pdf](https://github.com/pteridogroup/ppg/files/12423512/Ponce.Scataglini_Further.progress.towards.the.delimitation.of.Cheilanthes_ODAE2018.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by gyatskievych** [comment]
According to IPNI, only two species have combinations in Pellaeopsis: P. articulata and P. burkei.  Shouldn't the formal recognition of Pellaeopsis in PPG II wait until the circumscription of the genus has been described in more detail, or at least until the majority of the species have been transferred into it?  From what I see from the literature on African and Malagasy plants (cited in Tropicos under Synonymy of Pellaea angulosa), there is considerable disagreement on the limits of some species, especially Pellaea angulosa.

**Comment by MoniPonce** [comment]
In relation to the comments on our proposals (#41 and #42), we are submitting the advances presented at the XXXIX Jornadas Argentinas de Botánica held in September 2023.
[Poster Pellaeopsis - Choristosoria- PPG2.pdf](https://github.com/pteridogroup/ppg/files/12719182/Poster.Pellaeopsis.-.Choristosoria-.PPG2.pdf)

**Comment by MoniPonce** [comment]
We obtained good support for two groups of species belonging to Cheilanthes, Doryopteris and Pellaea from Africa and Madagascar that should be transferred to the genera Pellaeopsis J. Sm. and Choristosoria Mett. ex Kuhn. These assigments would improve the generic limits. This would not be an obstacle to examine the specific delimitation of each taxa of these genera. Consequently, if there is consensus to restore the old names, new combinations would be necessary for several Choristosoria and Pallaeopsis species names.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 4 (voting period October 2023). A total of 51 votes were cast. There were 31 'Yes' votes (60.8%) and 20 'No' votes (39.2%). The proposal does not pass.
