### ISSUE TITLE
Recovery of Choristosoria  (Pteridaceae) [NOT PASSSED]

### ISSUE THREAD

**Issue by MoniPonce** [pteridogroup/ppg#42]
### Author(s) of proposal

M. M. Ponce and M. A. Scataglini

### Name of taxon

Choristosoria Mett. ex Kuhn

### Rank of taxon

Genus

### Approximate number of species affected

Eight

### Description of change

Eight species from Africa and Madagascar, usually assigned to _Cheilanthes_ s.l. or _Pellaea_ s.l., would correspond to the monotypic paleotropical genus _Choristosoria_ Mett. ex Kuhn, 1879

### Reason for change

Eight paleotropical species (_Cheilanthes induta, C. multifida, C. namaquensis, C. quadripinnata, Pellaea calomelanos, P. involuta, P. pteroides_ and _P. viridis_), belonging to the clade of the South American genera _Adiantopsis_, _Doryopteris_ and _Mineirella_, appear in our phylogeny, joined with 98% support in a clade that would correspond to the monotypic genus _Choristosoria_ Mett. ex Kuhn, 1879, based on _C. pteroides_).
Some of these species were previously included in the "Choristosoria grade", but without support, in the phylogeny of Yesilyurt et al. 2015.
The relationships between the clade proposed here as _Choristosoria_ and the three  related South American genera mentioned above, could not been resolved yet with the plastid markers used.
The eight species clustered in our phylogeny differ from _Cheilanthes_ by their pinnae or ultimate segments hastate or ovate-hastate; laminar margins finely crenate-dentate (vs. ultimate segments ovate, triangular, oblong or linear; laminar margins entire or lobulate); and from _Pellaea_ differ by their laminae usually pedate-pinnatifid up to pedate-4-pinnate, having the basal basiscopic portions of the basal pinnae more developed or divided, (vs. pinnate up to 3-pinnate, not pedate); indusia discrete, lobulate, truncate or oblong, membranous (vs. indusia continuous, slightly or strongly revolute, unmodified or slightly hyaline tissue). 

### Reference(s) for publication of the name

[Yesilyurt et al_Doryopteris_Phytotaxa 221 (2) 101–122.pdf](https://github.com/pteridogroup/ppg/files/12423569/Yesilyurt.et.al_Doryopteris_Phytotaxa.221.2.101.122.pdf)
[Ponce & Scataglini_Phylogeny of Cheilanthesof and new genus Mineirella.pdf](https://github.com/pteridogroup/ppg/files/12423579/Ponce.Scataglini_Phylogeny.of.Cheilanthesof.and.new.genus.Mineirella.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by MoniPonce** [comment]
In relation to the comments on our proposals (https://github.com/pteridogroup/ppg/issues/41 and https://github.com/pteridogroup/ppg/issues/42), we are submitting the advances presented at the XXXIX Jornadas Argentinas de Botánica held in September 2023.
[Poster Pellaeopsis - Choristosoria- PPG2.pdf](https://github.com/pteridogroup/ppg/files/12719182/Poster.Pellaeopsis.-.Choristosoria-.PPG2.pdf)

**Comment by SchneiderHarald** [comment]
It is nice to see the reintroduction of a long forgotten generic concept. However, I am wondering if the generic boundaries have been already sufficiently clarified.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 4 (voting period October 2023). A total of 47 votes were cast. There were 28 'Yes' votes (59.6%) and 19 'No' votes (40.4%). The proposal does not pass.
