### ISSUE TITLE
Recognition of Dipteridales and Matoniales [NOT PASSED]

### ISSUE THREAD

**Issue by jessiepelosi** [pteridogroup/ppg#44]
### Author(s) of proposal

Jessie Pelosi and Augstina Yañez

### Name of taxon

Dipteridales, Matoniales 

### Rank of taxon

Order

### Approximate number of species affected

15 spp. (Dipteridaceae: 11 spp, 2 genera, Matoniaceae: 4 spp, 2 genera)

### Description of change

Recognition of Dipteridales (Dipterdiaceae including Dipteris and Cheiropleuria) and Matoniales (Matoniaceae including Matonia and Phanerosorus). 

### Reason for change

Several recently published phylogenomic studies have recovered that Gleicheniales is not monophyletic (Rothfels et al., 2015; Qi et al., 2018; Du et al., 2022; Nitta et al., 2022; Pelosi et al., 2022), whereas earlier phylogenetic works recovered that Gleicheniales was a clade consisting of Dipteridaceae, Gleicheniaceae, and Matoniaceae (1 plastid gene in Hasbee et al., 1995; 3 plastid genes and 1 nuclear gene in Pryer et al., 2004; 3 plastid genes in Schuettpelz and Pryer, 2007). The degree of the support for this clade, however, varies between studies from minimal in Hasbee et al. (1995) to moderate (Pryer et al., 2004; Schuettpelz and Pryer, 2007). Increases in the resolution of the fern tree of life with thousands of nuclear loci suggests that there is a high level of gene conflict in this area (e.g., see Figure 3 in Pelosi et al., 2022). PPG I cites Pryer et al. (2004) to support the recognition of a monophyletic Gleicheniales; recent genome-wide evidence, however, suggests that this order is not monophyletic and given that monophyly is the primary criterion for taxon acceptance Gleicheniales _senu lato_ should be revised. 

Matoniaceae and Dipteridaceae regularly form a clade sister to Gleicheniaceae (Pryer et al., 2004; Schuettpelz and Pryer, 2007; Testo and Sundue, 2016; Du et al., 2022; Nitta et al., 2022; Shu et al. 2022). However, the divergence between the two families is deep and occurred sometime in the middle or late Triassic (Skog, 2001; Tidwell & Ash, 1994; Schuettpelz and Pryer, 2009; Testo and Sundue 2016; Shu et al., 2022) and the study of fossil and current species shows very distinctive vegetative and reproductive morphological differences between both groups (Choo & Escapa, 2018; Yañez et al. 2023). The main differences are 1. Dipteridaceae taxa have non-indusiate sori usually distributed across the entire surface of the lamina, while in Matoniaceae the sori are usually organized in one (occasionally two or four) concentric rows around a prominent central area named receptacle or placenta, distributed on both sides of the midveins and sometimes protected by peltate indusium; 2. Dipteridaceae taxa have anastomosing veins with free-ending veinlets, while in Matoniaceae the veins are free or anastomosing, but never with free-ending veinlets.

In light of recent publications that have consistently shown that Gleicheniales is indeed not monophyletic, the deep divergence between Dipteridaceae and Matoniaceae, and distinctive vegetative and reproductive morphology, we propose that PPG II recognize Gleicheniales consisting of only Gleichenaceae (_Gleichenia, Gleichennela, Dicranopteris, Diplopterygium, Rouxopteris, Sticherus,_ and _Stromatopteris_), Dipteridales consisting of Dipteridaceae (_Dipteris_ and _Cheiropleuria_), and Matoniales consisting of Matoniaceae (_Matonia_ and _Phanerosorus_). 

It should be noted that in families such as Dipteridaceae and Matoniaceae where past diversity is much broader than current diversity, it is important to consider the divergence times and the morphology of both current and fossil taxa, in addition to the molecular evidence, to make decisions regarding its classification.

Literature Cited: 

- Choo, T.Y.S, and I.H. Escapa. 2018. Assessing the evolutionary history of the fern family Dipteridaceae (Gleicheniales) by incorporating both extant and extinct members in a combined phylogenetic study. Am J Bot 105(8):1-14.
- Du, X-Y., L-Y. Kuo, Z-Y. Zuo, D-Z. Li, and J-M. Lu. 2022. Structural variation of plastomes provides key insight into the deep phylogeny of ferns. Front Plant Sci 13:862772. 
- Nitta, J.H., Schuettpelz, E., Ramírez-Barahona, S., and Iwasaki, W., 2022. An open and continuously updated fern tree of life. Front Plant Sci. 13:909768.
- Pelosi, J.A., E.H. Kim, W.B. Barbazuk, and E.B. Sessa. 2022. Phylotranscriptomics Illuminates the Placement of Whole Genome Duplications and Gene Retention in Ferns. Front Plant Sci 13:882441. 
- Pryer, K.M., E. Schuettpelz, P.G. Wolf, H. Schneider, A.R. Smith, and R. Cranfill. 2004. Phylogeny and evolution of ferns (monilophytes) with a focus on the early leptosporangiate divergences. Am J Bot 91(10):1582-1598. 
- Qi, X., Kuo, L-Y., Gou, C., Li, H., Li, Z., Qi, J., Wang, L., Hu, Y., Xiang, J., Zhang, C., Guo, J., H., C-H., and Ma., H. 2018. A well-resolved fern nuclear phylogeny reveals the evolution history of numerous transcription factor families. Molecular Phylogenetics and Evolution 127: 961-977.
- Rothfels, C.J., F-W., Li, E.M. Sigel, L. Huiet, A. Larsson, D.O. Burge, M. Ruhsam, M. Deyholos, D.E. Soltis, et al. 2015. The evolutionary history of ferns inferred from 25 low-copy nuclear genes. Am J Bot 102(7):1089-1107. 
- Schuettpelz, E. and K.M. Pryer. 2007. Fern phylogeny inferred from 400 leptosporangiate species and three plastid genes. Taxon 56(4):1037-1050. 
- Schuettpelz, E., and K.M. Pryer. 2009. Evidence for a Cenozoic radiation of ferns in an angiosperm-dominated canopy. PNAS 106(27):11200-11205. 
- Shu, J-P., H. Wang, H. Shen, R-J. Wang, Q. Fu, Y-D. Wang, Y-N. Jiao and Y-H. Yan. 2022. Phylogenomic analysis reconstructed the order Matoniales from paleopolyploidy veil. Plants 11(12): 1529. 
- Skog, J. E. 2001. Biogeography of Mesozoic leptosporangiate ferns related to extant ferns. Brittonia 53: 236–269. 
- Testo, W.L., and M. Sundue. 2016. A 4000-species dataset provides new insight into the evolution of ferns. Molecular Phylogenetics and Evolution 105:200-211. 
- Tidwell WD, Ash SR. 1994. A review of selected Triassic to Early Cretaceous ferns. Journal of Plant Research 107:417–442.
- Yañez, A., Escapa, I. H., & Choo, T. Y. 2023. Fertile Goeppertella from the Jurassic of Patagonia: mosaic evolution in the Dipteridaceae-Matoniaceae lineage. AoB Plants 15(4), plad007.

### Reference(s) for publication of the name

Matoniales: Matoniales Pic. Serm. ex Reveal in Phytologia 74: 175. 25 Mar 1993.
Dipteridales: Dipteridales Doweld, Tent. Syst. Pl. Vasc.: x. 23 Dec 2001. 

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by SchneiderHarald** [comment]
Actually, the evidence required to justify the recognition of these two orders is weak to not existence depending on the kind of analyses used in the studies. SO far, we lack a careful study that integrates sufficient molecular, morphological evidence and especially integrate a comprehensive paleontological research framework.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 4 (voting period October 2023). A total of 47 votes were cast. There were 25 'Yes' votes (53.2%) and 22 'No' votes (46.8%). The proposal does not pass.
