### ISSUE TITLE
Recognition of Ellipinema (Polypodiaceae) and rejection of synonymization of 6 well-established genera with Lepisorus [NOT PASSED]

### ISSUE THREAD

**Issue by gonggashan88** [pteridogroup/ppg#46]
### Author(s) of proposal

Li-Bing Zhang

### Name of taxon

Ellipinema, Lemmaphyllum, Lepidomicrosorium, Lepisorus, Neocheiropteris, Neolepisorus, Paragramma, Tricholepidium

### Rank of taxon

Genus

### Approximate number of species affected

40

### Description of change

A new genus, Ellipinema, was described by Zhang et al. (2020) to accommodate one newly sampled species with a surprising phylogenetic position so that the 6 Old World well-established genera and the species names under them can continue to be used.

In contrast, based on the similar results Zhao et al. (2019) lumped the all other 6 genera in Lepisorus and made dozens of new combinations.

These relevant 6 genera are Lemmaphyllum (ca. 10 spp.), Lepidomicrosorium (ca. 10 spp.), Neocheiropteris (2 spp.), Neolepisorus (6 spp.), Paragramma (2 spp.), Tricholepidium (ca. 8 spp.). Lepisorus itself contains ca. 80 spp. 

### Reason for change

Wang et al. (2010) resurrected Paragramma from a synonym of Lepisorus and re-circumscribed the tribe Lepisoreae (Polypodiaceae) to contain 7 genera, which were all accepted by PPG I (2016). Later, both Zhao et al. (2019) and Zhang et al. (2020) found a newly sampled species, Lepisorus jakonensis, from western China (also found in N India), to be the second diverging lineage in the tribe Lepisoreae. Zhao et al. (2019) thus lumped all other 6 genera in Lepisorus, made dozens of new combinations, and treated these genera as (new) sections in Lepisorus. In contrast, Zhang et al. (2020) took a different approach by describing a new genus, Ellipinema, to accommodate the single species Lepisorus jakonensis, so that the other morphologically diagnosable and well-established genera can be retained, minimizing the name instability. 

The 6 non-Lepisorus genera, synonymized by Zhao et al. (2019), have long been widely recognized (e.g., Ching, 1978a, b; Ching and Shing, 1983; Lin, 2000; Wang et al., 2010a, b; Zhang et al., 2013; Fraser-Jenkins, 2015; PPG I, 2016; Ebihara, 2017; Chen et al., 2019). 

Notably, Zhao et al. (2019) had very small taxon sampling of non-Lepisorus genera, e.g., 1 or 2 accessions only each from Lepidomicrosorium, Neocheiropteris, Paragramma, and Tricholepidium, and 4 accessions only from Neolepisorus. Additionally, the relationships among the non-Lepisorus genera, especially those of Neolepisorus were not well supported in Zhao et al. (2019). Compared to the previous studies, Zhang et al. (2020) achieved complete or near-complete sampling of the tribe, as estimated by PPG I. As a result, the most of the relationships presented in Zhang et al. (2020) were well-supported, particularly when compared to the other recent studies (Wang et al., 2010; Chen et al., 2019; Zhao et al., 2019). Based on the work of Zhang et al., 2020, it was clear that collapsing the 6 well-established genera to accommodate the surprising phylogenetic position of one species did little more than obscure the genetic diversity of the lepisoroids as done by Zhao et al. (2019).

One additional aspect to consider is that species of nearly all these six genera, particularly those of Neocheiropteris and Neolepisorus, have great value in horticulture. Changing their generic names would cause much confusion and inconvenience for horticulture industry.

Importantly, two generic names Zhao et al.'s (2019) lumped in Lepisorus, Lemmaphyllum (1851) and Neocheiropteris (1905), are much older than Lepisorus (1933), threatening the application of Lepisorus, the largest genus in the tribe. Wei & Zhao (2019) thus proposed to conserve Lepisorus against Lemmaphyllum and Neocheiropteris, complicating the matter further. The fate of their proposal depends on the Botanical congress in 2024, causing a dilemma for PPG II now. What if their proposal is rejected?

Indeed, Ellipinema hybridized with one species of Lepisorus, but this issue has been solved by the description of a hybrid genus: xEllipisorus (Zhang & Zhang, 2020). Hybrid genera are rare but still acceptable in ferns. Again, only one name is affected. 

Wei et al. (2021) presented two nuclear trees of the tribe with relatively poor and somehow conflicting resolution based on a small sampling in a short communication in MPE (? not peer-reviewed). They proposed some ancient hybridization and incomplete lineage sorting (ILS) for the poor and conflicting resolution, which were hardly convincing at all. If the incongruence is largely due to ILS, the plastid trees in Zhao et al. (2019) and Zhang et al. (2020) are more accurate, since plastid coalesces more rapidly.

In summary, it seems to be the best and simplest practice to recognize Ellipinema due to deep phylogenetic divergence, morphological diagnosability, and nomenclatural stability. 

### Reference(s) for publication of the name
Important references:

Wang, L., Wu, Z.-Q., Xiang, Q.-P., Heinrichs, J., Schneider, H., Zhang, X.-C., 2010. Molecular phylogeny and a revised classification of tribe Lepisoreae (Polypodiaceae) based on an analysis of four plastid DNA regions. Bot. J. Linn. Soc. 162, 28–38. https://doi.org/10.1111/j.1095-8339.2009.01018.x
[Wang Li et al. 2010_Lepisoreae.pdf](https://github.com/pteridogroup/ppg/files/12665232/Wang.Li.et.al.2010_Lepisoreae.pdf)

Chen, C.-C., Hyvönen, J., Schneider, H., 2019. Exploring phylogeny of the microsoroid ferns (Polypodiaceae) based on six plastid DNA markers. Mol. Phylogenet. Evol., 106665.
[Chen et al. 2019 microsoroid ferns.pdf](https://github.com/pteridogroup/ppg/files/12665308/Chen.et.al.2019.microsoroid.ferns.pdf)

Zhao, C.-F., Wei, R., Zhang, X.-C., Xiang, Q.-P., 2019. Backbone phylogeny of Lepisorus (Polypodiaceae) and a novel infrageneric classification based on the total evidence from plastid and morphological data. Cladistics 1–24. https://doi.org/10.1111/cla.12403.
[Zhao et al. 2019 Lepisorus.pdf](https://github.com/pteridogroup/ppg/files/12665241/Zhao.et.al.2019.Lepisorus.pdf)

Wei, R., Zhao, C-F. 2019. Proposal to conserve Lepisorus nom. cons. against the additional names Lemmaphyllum and Neocheiropteris (Pteridophyta, Polypodiaceae). Taxon 68 (6): 1363–1371.
[Wei & Zhao 2019_ Proposal to conserve Lepisorus.pdf](https://github.com/pteridogroup/ppg/files/12666256/Wei.Zhao.2019_.Proposal.to.conserve.Lepisorus.pdf)

Zhang, L, Zhou, X-M, Liang, Z-L, Fan, X-P, Lu, NT, Song, M-S, Knapp, R, Gao, X-F, Sun, H, Zhang, L-B. 2020. Phylogeny and classification of the tribe Lepisoreae (Polypodiaceae; pteridophyta) with the description of a new genus, Ellipinema gen. nov., segregated from Lepisorus. Molecular Phylogenetics and Evolution 148 (July 2020): 106803. doi: https://doi.org/10.1016/j.ympev.2020.106803.
[Zhang et al. 2020_Lepisoreae_Ellipinema.pdf](https://github.com/pteridogroup/ppg/files/12665244/Zhang.et.al.2020_Lepisoreae_Ellipinema.pdf)

Wei, R., Zhao, C-F, Xiang, Q-P, Zhang, X-C. 2021. Ellipinema and ×Ellipisorus? Just Lepisorus (Polypodiaceae)! Molecular Phylogenetics and Evolution. 161: https://doi.org/10.1016/j.ympev.2021.107176.

### List the numbers of any related issues

#47 

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment]
>The fate of their proposal depends on the Botanical congress in 2024, causing a dilemma for PPG II now. What if their proposal is rejected?

I would just like to clarify the policy about cases where a PPG proposal depends on a nomenclatural change that needs to be approved by IBC. Our current policy is that such proposals may be voted on by PPG as long as a formal nomenclatural proposal to IBC has been submitted. For more details, please see the Discussion, ["How to proceed when PPG proposals are related to proposals before the IBC nomenclature committee"](https://github.com/pteridogroup/ppg/discussions/45).

**Comment by SchneiderHarald** [comment]
It is not task of PPGII to handle proposals that are part of the decision making process during the taxonomy meetings held in association with IBC meetings. Thus, I would prefer that this proposal is eliminated from the discussions at this stage.

**Comment by joelnitta** [comment]
@SchneiderHarald did you see my post above? I believe our current policy is to allow such PPG proposals as long as a nomenclatural proposal to IBC has been submitted (not necessarily yet passed at the IBC meeting).

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 5 (voting period November 2023). A total of 64 votes were cast. There were 18 'Yes' votes (28.1%) and 46 'No' votes (71.9%). The proposal does not pass.
