### ISSUE TITLE
recognize nothgenus xCystocarpium (Cystopteris x Gymnocarpium) [PASSED]

### ISSUE THREAD

**Issue by crothfels** [pteridogroup/ppg#5]
### Name of taxon

xCystocarpium

### Rank of taxon

Nothogenus

### Approximate number of species affected

1

### Description of change

This proposal is to recognize the nothogenus, xCystocarpium, between the genera Cystopteris and Gymnocarpium. xCystocarpium contains a single recognized species, xCystocarpium roskamianum Fraser-Jenk.

### Reason for change

Notho taxa were not recognized in PPG I, but we're planning on including them in PPG II, so a proposal is necessary. The two parental genera (_Cystopteris_ and _Gymnocarpium_) were each recognized in PPG I and I'm not aware of any suggestion to consider lumping them together (historically they were often thought to be in different families from each other). The parentage of the _xCystocarpium_ _roskamianum_ was initially hypothesized based on morphological data (Fraser-Jenkins 2008) and has been confirmed with low-copy nuclear data: one parent is _G.dryopteris_ and the other is a Eurasian member of the _C.fragilis_ complex (Rothfels et al. 2015). _xCystocarpium roskamianum_ is a robust plant, but is sterile, presumably due to meiotic difficulties: it is a recently formed allotetraploid of two other allotetraploids (so has four distinct subgenomes), and the parental genera themselves are inferred to have diverged from each other ~60 million years ago.

Christopher Fraser-Jenkins. 2008. Taxonomic revision of three hundred Indian subcontinental pteridophytes with a revised census-list: A new picture of fern-taxonomy and nomenclature in the Indian subcontinent. Bishen Singh Mahendra Pal Singh, Dehra Dun, India.

Carl J. Rothfels, Anne K. Johnson, Peter H. Hovenkamp, David L. Swofford, Harry C. Roskam, Christopher R. Fraser-Jenkins, Michael D. Windham, and Kathleen M. Pryer. 2015. Natural Hybridization between Genera That Diverged from Each Other Approximately 60 Million Years Ago. American Naturalist 185:3, 433-442. https://www.journals.uchicago.edu/doi/abs/10.1086/679662

[Rothfels et al.AmerNat.2015.pdf](https://github.com/pteridogroup/ppg/files/11500059/Rothfels.et.al.AmerNat.2015.pdf)

### Reference(s) for publication of the name

Christopher Fraser-Jenkins. 2008. Taxonomic revision of three hundred Indian subcontinental pteridophytes with a revised census-list: A new picture of fern-taxonomy and nomenclature in the Indian subcontinent. Bishen Singh Mahendra Pal Singh, Dehra Dun, India.

Fraser-Jenkins,  C.  R.,  Y.  P.  S.  Pangtey,  and  S.  P.  Kullar.  2010. _Asplenium laciniatum_ D. Don (Aspleniaceae), a critical complex, and confused species in the Indian subcontinent. Indian Fern Journal 27:212–214. (This publication makes the orthographic correction of "roskumianum" to "roskamianum".)

[Fraser-Jenkins_2010_Indian_Fern_Journal.pdf](https://github.com/pteridogroup/ppg/files/11500053/Fraser-Jenkins_2010_Indian_Fern_Journal.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by msbarkerAZ** [comment]
I support this proposal. Good evidence for this intergeneric hybrid and no good reason to combine these genera.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 1 (voting period July 2023). A total of 63 votes were cast. There were 60 'Yes' votes (95.2%) and 3 'No' votes (4.8%). The proposal passes.

**Comment by joelnitta** [comment]
Already implemented in data, closing.
