### ISSUE TITLE
Saccolomataceae genera: Saccoloma s.l. or Saccoloma s.str. and Orthiopteris?

### ISSUE THREAD

**Issue by schwartsburd** [pteridogroup/ppg#54]
### Author(s) of proposal

Pedro B. Schwartsburd

### Name of taxon

Saccoloma and Orthiopteris

### Rank of taxon

Genus

### Approximate number of species affected

25

### Description of change

There has been about four genera described that are related to what we understand now as Saccolomataceae. Among these four genera, two has been synonymized a long time ago, and they represent no issues for now. The other two names (Orthiopteris and Saccoloma) are still sometimes used, but in some different point of views, of which we should opt and adapt to use in PPG II.
1. The 1st is the broad conception that some authors adopt, considering only one genus, Saccoloma s.l., and placing Orthiopteris in synonymy. For example, Tryon & Tryon (1982), Kramer & Green (1990), PPG I (2016), Schwartsburd (2022). 
2. The second conception adopts Saccoloma s.str. for the 1-pinnate species of Saccolomataceae, and Orthiopteris for the 2-4-pinnate species. For example, Sehnem (1972), Luong et al. (2015).

The firsts phylogenies including Saccolomataceae species showed a polyphyletic group, but this was later questioned, and the new evidence arouse that some samples might have been mislabelled, contaminated or mis-identified - see PPG I (2016: 576), Schwartsburd (2022: 157). The only comprehensive phylogeny of Saccolomataceae that I am aware of is the provisional one that I generated in my taxonomic review of the Brazilian species (Schwartsburd 2022: Fig. 1), using three chloroplast genes.
My conclusions were:

1. Adopting Saccoloma s.str. for the 1-pinnate species, and Orthiopteris for the 2-4-pinnate is not monophyletic. The 1-pinnate species are nested within the 2-4-pinnate.
2. There are two geographical clades: a Paleotropical and a Neotropical. Orthiopteris and Saccoloma s.str. may be adopted, since their types are respectively Paleotropical and Neotropical. But, genera differentiation would be based on geographical distribution or on morphological differences not yet pointed out. Laminar dissection does not work, since in the Neotropics both 1-pinnate and 2-4-pinnate species occur.
4. Since I have not found any good morphological character to separate (Paleotropical) Orthiopteris from (Neotropical) Saccoloma s.str., I suggested the adoption of Saccoloma s.l. (with Orthiopteris in synonymy), for both Neotropical and Paleotropical species.

### Reason for change

My proposal is: we vote to decide if we adopt Saccoloma s.l. in PPG II, or Saccoloma s.str. and Orthiopteris (but in a monophyllectic manner). Therefore, we could vote as: 
1. We vote YES, and adopt only Saccoloma s.l. (with Orthiopteris in synonymy);
or
2. We vote NO, and adopt Saccoloma s.str. for the Neotropical species, and Orthiopteris for the Paleotropical species.

 Sorry adapting the issue in this format, but I thought it would be easier to handle (instead of creating two antagonic issues) 

### Reference(s) for publication of the name

[Saccoloma_Brazil_paginado.pdf](https://github.com/pteridogroup/ppg/files/13340798/Saccoloma_Brazil_paginado.pdf)

Kramer, K. U. 1990 Dennstaedtiaceae. Pp. 81–94 in: K.U. Kramer & P. S. Green (eds.), Vol. I Pteridophytes and Gymnosperms, In: K. Kubitzki (ed.), The Families and Genera of Vascular Plants. Springer-Verlag, Berlin.

Luong, T. T., P. H. Hovenkamp & M. S. M. Sosef. 2015. Revision of the fern genus Orthiopteris(Saccolomataceae) in Malesia and adjacent regions. PhytoKeys 53: 39–71. https://doi.org/10.3897/phytokeys.53.4955

Schwartsburd, P.B. 2022. The fern genus Saccoloma (Saccolomataceae) in Brazil, including new species and new combinations. Brittonia, 74(2): 155–179. https://doi.org/10.1007/s12228-021-09689-2 

Sehnem, A. 1972. Pteridáceas. In: R. Reitz (ed.), Flora Ilustrada Catarinense, part I, fasc. PTER. Herbário Barbosa Rodrigues, Itajaí.

Tryon, R. M. & A. F. Tryon. 1982. Ferns and allied plants, with special reference to tropical America. Springer-Verlag, New York.

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment]
@schwartsburd thanks for the proposal.

Your first option (*Saccoloma* s.l. with *Orthiopteris* in synonymy) is already used in PPG I, so there is no need to vote on it.

You seem to be arguing against the second option since you say "I have not found any good morphological character to separate (Paleotropical) *Orthiopteris* from (Neotropical) *Saccoloma* s.str."

So it seems there is nothing to vote on here, and I am closing (disregarding) this proposal.

If you *do* want to propose the second the option, please feel free to edit your text above and re-open this issue.
