### ISSUE TITLE
Recognition of Goswamia, Haukia, and Whittieria, segregates of Ophioglossum s.l. [NOT PASSED]

### ISSUE THREAD

**Issue by gonggashan88** [pteridogroup/ppg#69]
### Author(s) of proposal

Li-Bing Zhang, Liang Zhang

### Name of taxon

Goswamia, Haukia, Whittieria

### Rank of taxon

Genus

### Approximate number of species affected

20

### Description of change

Ophioglossum s.l. (PPG I, 2016) is split into Ophioglossum s.s., Goswamia, Haukia, and Whittieria.

### Reason for change

Based on deep divergences, morphology, developmental data (spore germination times), distributions, and ancient splits (129-179 mya vs. 18, 99, 40, and 21 mya for Botrychium, Botrypus, Japanobotrychium, and Sceptridium, respectively, in the same family), Zhang & Zhang (2022) described Goswamia, Haukia, and Whittieria, segregates from Ophioglossum s.l. A new study based on mitochondrial and plastome data (Kuo et al., 2023) resolved the South African endemic Rhizoglossum (sampled for the first time) as sister to the American endemic Whittieria (W. engelmannii = O. engelmannii). If Rhizoglossum with the special sporophores arising from the rhizome is to be recognized as PPGI (2016) did, Goswamia, Haukia, and Whittieria need to be recognized, so that the monophyly of Ophioglossum can be retained.

Morphological and geographical differences among these segregates and Ophioglossum s.s. see Zhang & Zhang (2022) pages 21-22 and Kuo et al. (2023, to be available online; figure below).

Alternatively, these segregates can be all merged and we can continue to recognize Ophioglossum s.l. alone, but this genus would then have very little molecular synapomorphies (short branch) and weak support (31% ML bootstrap) based on Kuo et al. (2023; figure below). 

One can even merge Ophioglossum s.l. with Ophioderma (ribbon ferns) and Cheiroglossa (hand ferns) so that the whole Ophioglossoideae contain only one genus with numerous molecular synapomorphies and strong support, but we would lose the well defined and horticulturally important Cheiroglossa (a few spp.) and Ophioderma (ca. 20 spp.).

![Ophioglossaceae tree_Kuo et al  2023](https://github.com/pteridogroup/ppg/assets/126826777/41256fca-5293-4da2-994f-3493fb21867e)

### Reference(s) for publication of the name

Zhang & Zhang 2022. Phylogeny, character evolution, and systematics of the fern family Ophioglossaceae based on Sanger sequence data, plastomes, and morphology. MPE. 173: 107512.
[Zhang & Zhang 2022_Ophioglossaceae classification.pdf](https://github.com/pteridogroup/ppg/files/13811577/Zhang.Zhang.2022_Ophioglossaceae.classification.pdf)

Kuo et al., Organellar phylogenomics of Ophioglossaceae fern genera. 2023(2024). doi: 10.3389/fpls.2023.1294716.
https://www.frontiersin.org/articles/10.3389/fpls.2023.1294716/abstract

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by leonperrie** [comment]
While the ML support value for Ophioglossum s.l. (including the Rhizoglossum, Whittieria, Goswamia, and Haukia lineages) is low in Kuo et al. (2024), it seems that its monophyly has not been conclusively rejected.  Might it then be argued that the taxonomically conservative decision is to keep a broad Ophioglossum, subsuming Rhizoglossum?  That would entail a single name change from PPG I (or even retain the status quo, pending resolution).

Notably, there was strong support for Ophioglossum s.l. with some tree-building methods in Zhang & Zhang (2022).  I’m not clear on what underlies this discrepancy.

Hopefully, data from the nuclear genome will provide conclusive resolution, and that seems the time to implement taxonomic changes, if needed.


Separately, I’m curious that the “Reason for change” begins with “Based on deep divergences…”.  Some (many?) taxonomists acknowledge there is no chronological equivalency across taxa recognised at a given rank; some are comfortable with this or at least reconciled to it.  For those wanting some equivalency, might it be prudent to achieve a consensus on age ranges for key taxonomic ranks before employing this reasoning?  It otherwise appears rather arbitrary.

**Comment by gonggashan88** [comment]
Hi Leon, thanks for comments. Yes, molecular evidence so far has not been strong, although an unresolved polytomy is not a piece of evidence to lump Rhizoglossum into Ophioglossum s.l.

I agree that divergence times have not yet been used consistently across different orders and families. However, should we use them more or less consistently within a specific family, here Ophioglossaceae? As I stated, Botrychium, Botrypus, Japanobotrychium, and Sceptridium diverged 18, 99, 40, and 21 mya, respectively, and are readily recognized as genera (PPG I, and probably PPG II), then should Goswamia, Haukia, and Whittieria (and Rhizoglosslum) that diverged 129-179 mya be also recognized as genera in the same family?

Morphologically, differences among Goswamia, Haukia, Whittieria, and Rhizoglosslum are probably clearer than those among Botrychium, Botrypus, Japanobotrychium, and Sceptridium. For example, Whittieria is the only taxon in the family with double venation, Haukia in the only taxon in the family with indumentum inside the rhizome, and disclike gametophytes and the only taxon in the New World with a tuberose rhizome, and Goswamia is the only taxon in the Old World with a tuberose or globose rhizome. These are all easily distinguishable from Ophioglossum s.s. with a cylindrical rhizome.

Of course, taxonomic ranks are completely arbitrary, but we may want to be consistent at least within a specific family.

**Comment by htuom** [comment]
I would definitely prefer a broadly defined Ophioglossum to the splitting proposed here. The segregate genera only contain a couple of species each, and their morphological separation from Ophioglossum does not seem particularly compelling. They could be recognised at the subspecific rank instead.

The same is actually true for the genera  that have been segregated from Botrychium. If consistency in divergence times of genera is aimed at, a broad circumscription of both genera would fit the bill.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 9 (voting period March 2024). A total of 78 votes were cast. There were 34 'Yes' votes (43.6%) and 44 'No' votes (56.4%). The proposal does not pass.
