### ISSUE TITLE
Recognition of Sahashia (Ophioglossaceae: Botrychioideae)

### ISSUE THREAD

**Issue by gonggashan88** [pteridogroup/ppg#70]
### Author(s) of proposal

Li-Bing Zhang, Liang Zhang

### Name of taxon

Sahashia

### Rank of taxon

Genus

### Approximate number of species affected

1

### Description of change

Segregating Sahashia from Botrupus s.l.

### Reason for change

Botrypus strictus and B. virginianus have been consistently found to be paraphyletic in relation to the rest of Botrychioideae (Hauk et al., 2003; Shinohara et al., 2013; Zhang et al., 2020; Zhang & Zhang, 2022; Kuo et al., 2023). Thus, Sahashia was described to accommodate Botrypus strictus so that the monophyly of Botrypus can be retained.

Sahashia is defined by the sporophores that are a compact panicle. Geographically, the only species of Sahashia occurs in East Asia and the Far East of Russia, whereas those of the newly defined Botrypus have sporophores as an open panicle and are distributed in temperate regions within the Northern Hemisphere and Central and South Americas. 

### Reference(s) for publication of the name

[Hauk et al. 2003_Ophioglossaceae.pdf](https://github.com/pteridogroup/ppg/files/13813961/Hauk.et.al.2003_Ophioglossaceae.pdf)

[Shinohara et al. 2013_Ophioglossaceae.pdf](https://github.com/pteridogroup/ppg/files/13813967/Shinohara.et.al.2013_Ophioglossaceae.pdf)

[Zhang et al. 2020 Ophioglossaceae.pdf](https://github.com/pteridogroup/ppg/files/13813905/Zhang.et.al.2020.Ophioglossaceae.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by choess** [comment]
This proposal already passed; see https://github.com/pteridogroup/ppg/issues/14

**Comment by gonggashan88** [comment]
Oh, I see. Thanks
