### ISSUE TITLE
Recognition of ×Woodsimatium (Woodsiaceae) [NOT PASSED]

### ISSUE THREAD

**Issue by gonggashan88** [pteridogroup/ppg#74]
### Author(s) of proposal

Li-Bing Zhang, Ngan Thi Lu

### Name of taxon

×Woodsimatium

### Rank of taxon

Genus

### Approximate number of species affected

1

### Description of change

Transfer of one hybrid from _Woodsia_ to _×Woodsimatium_.

### Reason for change

Lu et al. (2019) proposed to recognize two genera, _Woodsia_ and _Physematium_, in Woodsiaceae consisting of ca. 65 species (instead of ca. 30 spp. in early estimation) based on deep divergence in the phylogeny, morphological diagnosability, and geographical differentiation (see previous proposal).

If this two-genus classification is accepted, the only hybrid between the two genera, _Woodsia_ _×abbae_ Butters in Amer. Fern J. 31: 18. 1941 (_Physematium oreganum_ subsp. _cathcartianum_ × _Woodsia_ _ilvensis_), can be accommodated in the intergeneric hybrid genus, _×Woodsimatium_. 

This intergeneric hybrid between the deeply diverged (ca. 45 million years ago; Ma) lineages is reminiscent of the French Pyreneen intergeneric hybrid ×_Cystocarpium_ _roskamianum_, whose parents have been dated to have diverged ca. 60 Ma (Rothfels et al., 2015). This slow evolution of reproductive isolation has been argued to potentially contribute to the lower species diversity in ferns in comparison with angiosperms. The identification and recognition of _×Woodsimatium_ is additional evidence that slower evolution of reproductive isolation in ferns compared to flowering plants may account for the relative paucity of fern species.

### Reference(s) for publication of the name

[Rothfels et al. 2015_AmerNat.pdf](https://github.com/pteridogroup/ppg/files/14270091/Rothfels.et.al.2015_AmerNat.pdf)
[Lu et al. 2019_Woodsia.pdf](https://github.com/pteridogroup/ppg/files/14270093/Lu.et.al.2019_Woodsia.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment]
@gonggashan88 do you know if the hybrid is fertile?

**Comment by gonggashan88** [comment]
@joelnitta Hi Joel, good question! According to Wagner (1987: 122; pdf below), the only hybrid between the two "genera" "... is always sterile and must be formed each time anew". 

[Wagner 1987_Hybrid Woodsia abbae.pdf](https://github.com/pteridogroup/ppg/files/15155739/Wagner.1987_Hybrid.Woodsia.abbae.pdf)

**Comment by joelnitta** [comment]
Thanks very much @gonggashan88 for sharing the paper! 

Just to clarify, the part you quoted is with respect to *W. x abbeae* found **in Michigan**: "*Woodwardia x abbeae* has been found in several localities in that state [Michigan]; it is always sterile..."

Also, Wagner (1987) does mention a partially fertile specimen:

> Butters and Tryon (1948) reported a partially fertile frond of *W. x abbeae*, the upper portion of which bore fertile
spores that germinated when sown. The lower half of the frond was sterile. Measurements that were made indicated that the fertile part of the leaf had probably become polyploid.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 10 (voting period April 2024). A total of 60 votes were cast. There were 27 'Yes' votes (45%) and 33 'No' votes (55%). The proposal does not pass.
