### ISSUE TITLE
Recognition of Lycopodiastroideae (Lycopodiaceae) [NOT PASSED]

### ISSUE THREAD

**Issue by gonggashan88** [pteridogroup/ppg#76]
### Author(s) of proposal

Li-Bing Zhang, Xin-Mao Zhou

### Name of taxon

Lycopodiastroideae

### Rank of taxon

Subfamily

### Approximate number of species affected

1

### Description of change

Recognition of Lycopodiastroideae to accommodate _Lycopodiastrum_ with unique morphology, spore ornamentation, and deep divergence from its relatives.

### Reason for change

The scabrate ornamentation of spores of _Lycopodiastrum_ was firstly reported by Wilce (1972) and confirmed by Chen (2019) and our photo (see Fig. 1), and is not compatible with the spore morphology of other Lycopodioideae sensu PPG I (2016). The other two subfamilies recognized by PPG I (2016) are well defined by spore ornamentation — Huperzioideae have foveolate-fossulate spores and Lycopodielloideae have rugulate or nearly reticulate spores — it is just Lycopodioideae that are heterogeneous in this regard (figure below). Morphologically, _Lycopodiastrum_ is also unique in the family in having climbing aerial shoots, and 6–26 strobili per peduncle that are terminal on multidichotomously branched peduncles (Zhang 2004; Zhang & Iwatsuki, 2013). Based on the deep divergence of _Lycopodiastrum_ from the remaining extant lineages, its scabrate spore ornamentation, and its unique macromorphology, a new subfamily, Lycopodiastroideae, has been proposed (Zhang & Zhou, 2022).

_Pseudolycopodium_ has baculate spores, also different from the reticulate spores in other Lycopodioideae s.s., but it would not be appropriate to separate _Pseudolycopodium_ from Lycopodioideae because it is resolved as a shallow clade in the phylogeny (figure below). 

Lycopodiastroideae contain a single genus: _Lycopodiastrum_, with a single species, _L. casuarinoides_, widely distributed in tropics and subtropics of Asia extending eastward to Papua New Guinea.

![Zhang   Zhou 2022_classification of Lycopodiales](https://github.com/pteridogroup/ppg/assets/126826777/98c276f5-7ebe-4e80-aecb-a45b078c4558)

![Untitled-1](https://github.com/pteridogroup/ppg/assets/126826777/4e41f515-4fae-492f-af8e-b0faffc9985b)

### Reference(s) for publication of the name

[Zhang & Zhou 2022_classification of Lycopodiales.pdf](https://github.com/pteridogroup/ppg/files/14276185/Zhang.Zhou.2022_classification.of.Lycopodiales.pdf)
[Chen et al 2022_Lycopodiaceae.pdf](https://github.com/pteridogroup/ppg/files/14276188/Chen.et.al.2022_Lycopodiaceae.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by EdgarJRincon** [comment]
Considero que la estructura y la ultraestructura de las esporas es un carácter confiable a tener en cuenta y más aún si este tipo de microornamehtación solo ha sido encontrada en Lycopodiastrum.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 10 (voting period April 2024). A total of 75 votes were cast. There were 32 'Yes' votes (42.7%) and 43 'No' votes (57.3%). The proposal does not pass.

**Comment by joelnitta** [comment]
Implemented in WFO: Lycopodiastroideae https://list.worldfloraonline.org/rhakhis/ui/index.html#wfo-4100000971
